#!/usr/bin/env python

import sys
from liblatexdiff import *

def scm_latexdiff(argv):
  ''' Calculate diff pdf between two latex files, either in hg, git, or a local file. '''
  showHelp(argv)
  git = gitOrHg()
  old_fileloc, new_fileloc = processCmdlineArgs(argv, git)
  old_texfile, new_texfile = dumpRepositoryVersion2tmp(old_fileloc, new_fileloc, git)
  createDiffTex(old_texfile, new_texfile, swaplocal = "local" in old_fileloc and not "local" in new_fileloc)
  compileDiffPdf("diff.log")
  cleanAllNonePDF()
  
if __name__ == "__main__":
  scm_latexdiff(sys.argv)

