#! /usr/bin/python

import sys, tempfile, pdb
from liblatexdiff import *

def showHelp(argv):
  try:
    old_fileloc = argv[1]
  except IndexError:
    printHelp()    
  if old_fileloc in ["-h","h","--help","help","--h"]:
    printHelp()    


if __name__ == "__main__":
  showHelp(sys.argv)
  git = gitOrHg()
  if git:
    print "Detected Git repository..."
  else:
    print "Detected Mercurial repository..."

  # Parsing input parameters
  old_fileloc, new_fileloc = processCmdlineArgs(sys.argv, git)
  
  # Dumping revisions to temporary files
  old_fo = open(tempfile.mkstemp()[1], "w")
  new_fo = open(tempfile.mkstemp()[1], "w")
  if git:
    dumpGitFile(old_fileloc, old_fo)
    dumpGitFile(new_fileloc, new_fo)  
  else:
    dumpHgFile(old_fileloc, old_fo)
    dumpHgFile(new_fileloc, new_fo)
  old_fo.close()
  new_fo.close()

  # Running latex diff
  diff_tex = open("diff.tex", "w")
  latexdiff(old_fo.name, new_fo.name, diff_tex)
  diff_tex.close()

  # Generating the pdf file
  f = open("diff.log", "w")
  compileDiffPdf(f)
  f.close()
  
  # Clean up
  os.system('mv diff.pdf /tmp')
  os.system('rm diff*')
  os.system('mv /tmp/diff.pdf .')
  
